# Generated by Django 2.0.7 on 2018-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180710_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='year',
            field=models.CharField(choices=[('Y18', 'Batch Of 2018'), ('Y17', 'Batch Of 2017'), ('Y16', 'Batch Of 2016'), ('Y15', 'Batch Of 2015')], max_length=3),
        ),
    ]
