# Generated by Django 2.0.6 on 2018-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.CharField(max_length=256)),
                ('to', models.CharField(max_length=256)),
                ('time', models.TimeField()),
                ('busno', models.IntegerField(blank=True)),
                ('operator', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='buswe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.CharField(max_length=256)),
                ('to', models.CharField(max_length=256)),
                ('time', models.TimeField()),
                ('busno', models.IntegerField(blank=True)),
                ('operator', models.CharField(max_length=256)),
            ],
        ),
    ]
