# Generated by Django 2.0.6 on 2018-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buswd',
            name='busno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buswe',
            name='busno',
            field=models.IntegerField(null=True),
        ),
    ]
