# Generated by Django 2.0.6 on 2018-07-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20180704_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='slotend',
            new_name='slten',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='slotstart',
            new_name='sltst',
        ),
    ]
