# Generated by Django 2.0.7 on 2018-07-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20180704_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='institute',
            field=models.CharField(default='LNMIIT', max_length=256),
            preserve_default=False,
        ),
    ]
