# Generated by Django 2.0.6 on 2018-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=256)),
                ('brk', models.CharField(max_length=256)),
                ('lun', models.CharField(max_length=256)),
                ('snk', models.CharField(max_length=256)),
                ('din', models.CharField(max_length=256)),
            ],
        ),
    ]
