# Generated by Django 2.0.7 on 2018-07-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='institute',
            field=models.CharField(default='LNMIIT', max_length=256),
            preserve_default=False,
        ),
    ]
